### ISSUE TITLE
Add license to project

### ISSUE THREAD

**Issue by rowanG077** [gergoerdi/clash-utils#1]
I'm interested in trying to use some parts of this project in my own clash project. However I can't do this since there is no license because I use clash at my company. Would it be possible to add permissive license?

**Comment by gergoerdi** [comment]
Sure, I'm happy to license this under the terms of the MIT license. I'll commit the "paperwork" later today. 

However, I cannot give any guarantees of API stability at this time. I am tracking CLaSH's `master` branch and I am also heavily refactoring my own stuff; also, everything here will at some point need to be high-quality enough (on the human readability axis) that I can include them in a book about CLaSH development.

**Comment by rowanG077** [comment]
Thanks!

I'm OK with the API not being stable. I'm tracking master of CLaSH as well so this is no issue for me.
